# gateway/src/main/resources/application.yml
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://userservice:8081
          predicates:
            - Path=/api/user/**
  zipkin:
    base-url: http://zipkin:9411
  sleuth:
    sampler:
      probability: 1.0

server:
  port: 8080